# Generated by Django 5.1.5 on 2025-02-10 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itinerary', '0002_activity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Activity',
        ),
        migrations.RenameField(
            model_name='travelplan',
            old_name='return_date',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='travelplan',
            old_name='travel_date',
            new_name='start_date',
        ),
        migrations.RemoveField(
            model_name='travelplan',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='travelplan',
            name='budget',
            field=models.CharField(choices=[('Low', 'Low'), ('Mid', 'Mid'), ('High', 'High')], max_length=50),
        ),
    ]
